runtime: php
env: flex

#[START env]
env_variables:
    # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
    # values obtained when configuring your Cloud SQL instance.
    MYSQL_DSN: mysql:dbname=HealthWealth;unix_socket=/cloudsql/dulcet-nucleus-168208:us-central1:healthwealth
    MYSQL_USER: root
    MYSQL_PASSWORD: root
#[END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "dulcet-nucleus-168208:us-central1:healthwealth"
#[END cloudsql_settings]
